---
title: "HW#3"
author: "Halid Kopanski"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
library(faraway)
library(car)
library(MASS)
library(lmtest)
library(tidyverse)
```

## LMR 4.1

```{r echo = FALSE}
pros_model1 <- lm(lpsa ~ ., data = prostate)
summary(pros_model1)
```

a)

```{r echo=FALSE}
new_patient <- tibble(lcavol = 1.44692,  lweight = 3.62301,  age = 65.00000, 
                      lbph = 0.30010,  svi = 0.00000,  lcp = -0.79851, 
                      gleason = 7.0000,   pgg45 = 15.0000)

predict(pros_model1, newdata = new_patient, interval = "confidence")
predict(pros_model1, newdata = new_patient, interval = "prediction")
mean(prostate$age)
```

b)

```{r echo = FALSE}
new_patient1 <- tibble(lcavol = 1.44692,  lweight = 3.62301,  age = 25.00000, 
                      lbph = 0.30010,  svi = 0.00000,  lcp = -0.79851, 
                      gleason = 7.0000,   pgg45 = 15.0000)

predict(pros_model1, newdata = new_patient1, interval = "confidence")
predict(pros_model1, newdata = new_patient1, interval = "prediction")
```

c)

```{r echo = FALSE}
pros_model2 <- lm(lpsa ~ lcavol + lweight + svi, data = prostate)
summary(pros_model2)
predict(pros_model2, newdata = new_patient1, interval = "confidence")
predict(pros_model2, newdata = new_patient1, interval = "prediction")
print(anova(pros_model2, pros_model1))
```

\newpage

# LMR 6.1

```{r echo = FALSE}
sat_model1 <- lm(total ~ expend + salary + ratio + takers, data = sat)
summary(sat_model1)
```

a)

```{r echo = FALSE}
plot(x = sat_model1$fitted.values, y = sat_model1$residuals, pch = 19,
     main = "Residuals vs Fitted Values", xlab = "Fitted Values", ylab = "Residuals")
res_line <- loess(sat_model1$residuals ~ sat_model1$fitted.values)
j <- order(sat_model1$fitted.values)
lines(sat_model1$fitted.values[j], res_line$fitted[j], col = "red", lwd = 3)
abline(h = 0)
```

Results of the Breusch - Pagan Test 

```{r echo = FALSE}
bptest(sat_model1, studentize = FALSE)
```

The results of the Non Constant Variance Test

```{r echo = FALSE}
ncvTest(sat_model1)
```

b)

```{r echo = FALSE}
qqnorm(sat_model1$residuals, ylab = "Residuals", main = "Q-Q Plot (Normality)", pch = 19)
qqline(sat_model1$residuals)
```

Results of the Shapiro and the Durbin-Watson Tests

```{r echo = FALSE}
shapiro.test(sat_model1$residuals)
dwtest(sat_model1)
```

c)

```{r echo = FALSE, fig.dim = c(6,6)}
X <- sat %>% select(expend, salary, ratio, takers)
X <- cbind(rep(1, nrow(X)), X)

X <- data.matrix(X)

#print(X)
Xt <- t(X)

XtX_inv <- solve(Xt %*% X)

XtY <- Xt %*% sat$total

beta_hat <- XtX_inv %*% XtY

P <- X %*% XtX_inv %*% Xt

res_mean <- mean(sat_model1$residuals)
res_sd <- sd(sat_model1$residuals)
stan_res <- (sat_model1$residuals - res_mean) / res_sd

plot(x = diag(P), 
     y = sat_model1$residuals, 
     pch = 19,
     main = "Residuals vs Leverage", 
     xlab = "Leverage", 
     ylab = "Residuals",
     xlim = c(0, 0.35))
text(diag(P), sat_model1$residuals, rownames(P), 
     cex = 0.6, pos = 4, col = "red")
```

```{r echo = FALSE}
hat_data <- cbind(1:50, diag(P))

plot(hat_data, pch = 19, xlab = "", ylab = "hii values")
abline(h = 2 * 5 / 50)
text(hat_data[,1], hat_data[,2], names(diag(P)), 
     cex = 0.5, pos = 4, col = "red")
```



```{r echo = FALSE, fig.dim = c(6,6)}
dotchart(sort(diag(P)), pch = 19, cex = 0.5)
```

d)

```{r echo = FALSE}
outlierTest(sat_model1)

plot(x = sat_model1$fitted.values, y = rstandard(sat_model1), pch = 19,
     main = "Standardized Residuals vs Fitted Values", xlab = "Fitted Values", ylab = "Standardized Residuals")
abline(h = c(0, 2, -2), col = "blue", lty = 4, lwd = 2)
text(x = sat_model1$fitted.values, y = rstandard(sat_model1), rownames(sat), 
     cex = 0.5, pos = 4, col = "red")
```

```{r echo = FALSE}
#cooks.distance(sat_model1)

halfnorm(diag(P), labs = rownames(P), ylab = "Leverages")
abline(h = 2 * sat_model1$rank / nrow(sat))

SST <- sum((sat$total - mean(sat$total))^2)
SSR <- sum((sat_model1$fitted.values - mean(sat$total))^2)
SSE <- sum((sat$total - sat_model1$fitted.values)^2)
MSR <- SSR/(sat_model1$rank - 1)
MSE <- SSE/(nrow(sat) - sat_model1$rank)
```

e)

```{r echo = FALSE, fig.dim = c(6,6)}
influenceIndexPlot(sat_model1)
```

```{r echo = FALSE, fig.dim = c(6,6)}
cooks_dis_calc <- sat_model1$residuals^2 / 
  (sat_model1$rank * MSE) * (diag(P)/(1-diag(P))^2)

dotchart(sort(cooks_dis_calc), cex = 0.5, pch = 19)
```

\newpage

# LMR 6.8

a)

```{r echo = FALSE}
fat_model1 <- lm(brozek ~ age + weight + height + neck + chest + 
                   abdom + hip + thigh + knee + ankle + biceps + 
                   forearm + wrist, data = fat)

X <- model.matrix(fat_model1)[,-1]
eigen_X <- eigen(t(X) %*% X)

sqrt(eigen_X$values[1]/eigen_X$values)

vif_x <- rep(0, ncol(X))


for(i in 1:ncol(X)){
    vif_x[i] <- 1 / (1 - summary(lm(X[,i] ~ X[,-i]))$r.squared)    
}

vif_x <- cbind(colnames(X), vif_x)
print(vif_x)
```

b)

```{r echo = FALSE}
new_fat <- fat[-c(39,42),]

fat_model2 <- lm(brozek ~ age + weight + height + neck + chest + 
                   abdom + hip + thigh + knee + ankle + biceps + 
                   forearm + wrist, data = new_fat)

X2 <- model.matrix(fat_model2)[,-1]
eigen_X2 <- eigen(t(X2) %*% X2)

sqrt(eigen_X2$values[1]/eigen_X2$values)

vif_x2 <- rep(0, ncol(X2))


for(i in 1:ncol(X2)){
    vif_x2[i] <- 1 / (1 - summary(lm(X2[,i] ~ X2[,-i]))$r.squared)    
}

vif_x2 <- cbind(colnames(X2), vif_x2)
print(vif_x2)
```

c)

```{r echo = FALSE}

fat_model3 <- lm(brozek ~ age + weight + height, data = new_fat)
summary(fat_model3)

X3 <- model.matrix(fat_model3)[,-1]
eigen_X3 <- eigen(t(X3) %*% X3)

sqrt(eigen_X3$values[1]/eigen_X3$values)

vif_x3 <- rep(0, ncol(X3))


for(i in 1:ncol(X3)){
    vif_x3[i] <- 1 / (1 - summary(lm(X3[,i] ~ X3[,-i]))$r.squared)    
}

vif_x3 <- cbind(colnames(X3), vif_x3)
print(vif_x3)

```

d)

```{r echo = FALSE}

fat_1 <- as.data.frame(t(apply(X3, 2, median)))

predict(fat_model3, newdata = fat_1, interval = "prediction")

```

e)

```{r echo = FALSE}

fat_2 <- as.data.frame(cbind(age = 40, weight = 200, height = 73))

predict(fat_model3, newdata = fat_2, interval = "prediction")

```

f)

```{r echo = FALSE}
fat_3 <- as.data.frame(cbind(age = 40, weight = 130, height = 73))

predict(fat_model3, newdata = fat_3, interval = "prediction")
```

\newpage

## Code
```{r, ref.label=knitr::all_labels(),echo=TRUE,eval=FALSE}
```